name: celebrations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP dependencies
        run: composer install 
      - name: Deployment of the app files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/RentverifyDashboard
            git checkout -f 
            git pull origin main
            composer install